# The URL the site will be built for
base_url = "https://lloydsrecords.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "no-style-please"

[markdown]
# Syntax highlighting is disabled by default; set [markdown.highlighting]
# options here if it's ever wanted (zola >= 0.22 syntax)


[extra]
# Put all your custom variables here

header_nav = [
    { name = "~home", url = "/" },
    { name = "#bllog", url = "/bllog" },
    { name = "$shop", url = "/shop" },
]
